### ISSUE TITLE
Formatting Issue with Projects on Firefox

### ISSUE THREAD

**Issue by Forsyth-Creations** [Amp-Lab-at-VT/Website#23]

**Comment by Forsyth-Creations** [comment]
![image](https://user-images.githubusercontent.com/33364183/219518608-38005cee-344a-4203-8b61-7189bf2a4348.png)

**Comment by sakgoyal** [comment]
The in the css, the `projectBoxImage` width value is not being set. firefox will default to `auto` which is causing problems. 
when I run the dev version and try to access the page, I get an error saying:
![image](https://user-images.githubusercontent.com/19929553/226077397-b2b13a8b-6ae9-42ce-be0b-091fd858ea4e.png)

I'm guessing this is happening because firefox is setting the box width to the full image size width. but when the image height is limited, the image is shown at a small size, but the width remains at the full scale.

**Comment by Forsyth-Creations** [comment]
Closed with NextJS migration
